# INSTAGRAM MODULE
logging_in_text = 'Initiating driver and logging in...'
# Follow Module
waiting_scrape_text = 'Scraping followers... Waited {} seconds so far'
restricted_account_text = 'Your account has been either restricted or blocked due to sospicious activity. Please open Instagram and log in and use it normally for at least 24 hours before trying again.'
starting_follows_text = '{}\'s followers have been scraped. Starting to follow {} users...'
followed_user_text = 'Followed {} user(s) out of {}...'
invalid_credentials_text = 'Your instagram credentials are incorrect... Please log int again with /login'
verification_code_necessary = 'Your instagram account has 2FA turned on... In order for the bot to work, please turn it off.'
private_account_error_text = 'The account {} is private - hence it\'s impossible to get it\'s followers. Please try again with another account using /follow'
operation_error_text = 'There was an error when executing your request... The developer has been informed.'
follow_successful_text = 'Operation successful! {} of {}\'s followers have been followed'
# Unfollow Module
retriving_follows_text = 'Retrieving followed accounts from database...'
initiating_unfollow_text = 'Starting to unfollow users...'
unfollowed_user_text = 'Unfollowed {} user(s) out of {}...'
unfollow_successful_text = 'Operation successful! {} users out of {} have been unfollowed.'
# Check Notifications Module
scraping_notifications_text = 'Retrieving notifications...'
checking_new_notifs_text = 'Checking for new notifications...'
no_new_notifications_found_text = 'No new notifications here!'
found_notifications_text = 'Found new notifications... Sending your regards to your {} new follower(s)...'
finished_notifications_text = 'All done here! Sent your regards to {} of your new follower(s)!'
checked_notis_no_followers = 'Checked notifications. No new followers to greet so far!'
inform_of_failed_text = '\n<b>I did not manage to contact the following users:</b>'


# START COMMAND
welcome = 'Hi! I will be your own FF Insta Bot, I\'ll help you automate some of those more repeatable tasks in Instagram - such as following, unfollowing users, or greeting new followers!\n\nLet\'s start by logging into your instagram account. Press Next to continue.'
end = 'Alright! You can now use this bot with the account <b>{}</b> as well! Check your notifications now so that we can start checking for new followers:'
startup_done = 'Seems you already have gone through the initial bot startup. You can edit your settings with the button below:'


# ACCOUNT COMMAND
checking_accounts_connection = 'Checking account connection...'
no_connection = 'No instagram connection found.'
problem_connecting = 'There was a problem when checking the connection... The developer has been notified.'
connection_found_text = '<b>Instagram Account</b>\nYou are currently logged into Instagram with the account <a href="https://www.instagram.com/{}/">{}</a>\nYou can switch account or log out entirely with the buttons below.'
switch_account_text = 'Select below the account you\'d like to switch to, or log into another account:'
no_accounts_available_text = 'No other accounts available. Click the button below to add another account to the selection.'
switched_account_text = 'You switched to the <a href="https://www.instagram.com/{}/">{}</a> account. The bot\'s commands will now affect that account.'


#INSTAGRAM LOGIN CONVERSATION
checking_ig_status = 'Checking instagram connection...'
user_logged_in_text = 'You are already logged in!'
checking_ig_credentials_text = 'Instagram is not connected. Checking credentials...'
logging_in_with_credentials_text = 'Instagram credentials found. Logging in...'
input_verification_code_text = 'Send below the verification code generated by your Authenticator App or that was sent to you via SMS by Instagram:'
input_security_code_text = 'Send below the security code that was sent to you via SMS by Instagram (The code might take up to a couple of minutes to get sent by Instagram\'s servers...): '
input_security_code_text_email = 'Send below the security code that was sent to you by Instagram via email to the email address tied to your account (The code might take up to a couple of minutes to get sent by Instagram\'s servers...):'
security_code_resent = 'The security code has been sent again via {} (attempt {})... Type it below:'
input_ig_username_text = 'Input below your instagram username:'
checking_user_vadility_text = 'Checking username vadility...'
invalid_user_text = 'The username you have provided, {}, does not exist. Please try again with a correct instagram username:'
input_password_text = 'Input your instagram password below:'
attempting_login_text = 'Attempting to log into instagram...'
invalid_password_text = 'The password you provided, {}, is incorrect. Please try again:'
login_successful_text = 'You successfully logged into your instagram account! \nNow please enter below the message you would like me to send to your new followers:'
validating_code_text = 'Validating instagram 2FA security code...'
invalid_security_code_text = 'The security code you provided is invalid. Please try again below:'
cancelled_instagram_text = 'Instagram log in procedure has been cancelled.'


# INSTAGRAM LOG OUT COMMAND
logging_out = 'Logging out of instagram...'
instagram_loggedout_text = 'Instagram log out successful! To log in again, use /login'
error_loggingout_text = 'There was an error when trying to log out of instagram... Try again later or contact a developer.'


# CHECK NOTIFS COMMAND
no_settings_found_text = 'No settings where found... Please use /start to set up the bot first.'


# FOLLOW CONVERSATION
select_account_text = 'Insert below the username of the account you want to scrape:'
error_when_checking_account = 'There was an error when checking {}\'s vadility... The account might be inexistent or private. Please choose another account:'
select_count_text = 'Select below the amount of users you would like to follow:'
confirm_follow_text = 'Are you sure you want to follow {} of {}\'s followers?'
launching_operation_text = 'Starting operation...'
follow_cancelled_text  = 'Follow request cancelled.'


# UNFOLLOW CONVERSATION
no_records_text = 'You haven\'t followed any selections of users yet. To do that, use /follow'
select_record_text = 'Select below the selection of user followers you would like to unfollow:'
error_retrieving_record_text = 'There was an error when retrieving information about your selection... the developer has been notified.'
confirm_unfollow_text = 'Are you sure you want to unfollow {} of {}\'s followers?'
unfollow_cancelled_text = 'Unfollow request cancelled.'


# SETTINGS CONVERSATION
select_setting_text = 'Select below which setting you would like to edit:'
select_frequency_text = 'Select below how often do you wish the bot to check your notifications:'
select_period_text = 'Select below for how long should the bot keep checking your notifications:'
select_text_text = 'Input below the message text you would like me to send to your new followers - note that emojis and special characters, as well as markdown formatting might not translate to Instagram formatting.'
edited_text_text = 'The default message text to greet new followers has been edited successfully!'
cancelled_editing_settings = 'Settings have not been altered.'


# GENERAL
incorrect_command_text = 'The command or message you sent is not a recognized command. Try /help for more information.'
# MULTIPLE UTILITIES
error_checking_connection = 'There was a problem in authenticating the client. Please try again or contact @davidwickerhf.'
incorrect_credentials_error = 'When sending the messages the client wasn\'t able to log into the account due to incorrect credentials... Please check and edit your credentials with /instagram\n{} Send DM requests completed so far.'
suspicious_login = 'There was a problem connecting to the client when processing your request... Please log out with /iglogout and then log back into the client with /instagram\n{} Send DM requests completed so far.'
verification_necessary = 'Your account has 2FA turned on. In order to process this request, you must turn 2FA off from your account.\n{} Send DM requests completed so far.'
restricted_account = 'Your account has been restricted from Instagram! \nLog into your account manually and try to engage with the website. Try to send this request again after at least 24 hours.\n{} Send DM requests completed so far.'
blocked_account = 'Your account has been blocked! \nLog into your account from your own device to unblock the account - then, wait at least 24 hours before sending another request\n{} Send DM requests completed so far.'
not_admin_text = 'Sorry, this command can only be used by an admin.'
not_authorized_text = 'You are not authorized to use this bot\'s features'
not_logged_in_text = 'To use this command you must log in first with /login'

# HELP COMMAND
help_text = '<b>FF INSTA BOT</b>\n/settings - Manage bot settings\n\n/account - Check instagram connection\n\n/login - Log into instagram\n\n/logout - Log out of instagram\n\n/follow - Follow a user\'s followers\n\n/unfollow - Unfollow previously followed users\n\n/checknotifs - Manually check incoming notifications\n\n/start - Run Bot Setup'